.MODEL SMALL
.STACK 100H

.DATA
    COURSES DB 'CSE110', 'CSE111', 'CSE220', 'CSE221', 'CSE341', 'CSE340', 'CSE471', 'CSE422', 'CSE423', 'CSE460'
    USER_INP DB ?
    MSG DB 'ENTER COURSE LEVEL (1, 2, 3, OR 4): $'
    MSG1 DB '100-LEVEL COURSES:', 0DH, 0AH, '$'
    MSG2 DB '200-LEVEL COURSES:', 0DH, 0AH, '$'
    MSG3 DB '300-LEVEL COURSES:', 0DH, 0AH, '$'
    MSG4 DB '400-LEVEL COURSES:', 0DH, 0AH, '$'
    COURSE_END DB 0DH, 0AH, '$'

.CODE
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX

    MOV DX, OFFSET MSG
    MOV AH, 09H
    INT 21H

    MOV AH, 01H
    INT 21H
    SUB AL, '0'
    MOV USER_INP, AL
    
    CMP AL, 1
    JE LEVEL1
    CMP AL, 2
    JE LEVEL2
    CMP AL, 3
    JE LEVEL3
    CMP AL, 4
    JE LEVEL4
    JMP ENDPGM

LEVEL1:
    MOV DX, OFFSET MSG1
    MOV AH, 09H
    INT 21H

    MOV SI, 0
    CALL PRINT_COURSE
    CALL PRINT_COURSE
    JMP ENDPGM

LEVEL2:
    MOV DX, OFFSET MSG2
    MOV AH, 09H
    INT 21H

    MOV SI, 12
    CALL PRINT_COURSE
    CALL PRINT_COURSE
    JMP ENDPGM

LEVEL3:
    MOV DX, OFFSET MSG3
    MOV AH, 09H
    INT 21H

    MOV SI, 24
    CALL PRINT_COURSE
    CALL PRINT_COURSE
    JMP ENDPGM

LEVEL4:
    MOV DX, OFFSET MSG4
    MOV AH, 09H
    INT 21H

    MOV SI, 36
    CALL PRINT_COURSE
    CALL PRINT_COURSE
    CALL PRINT_COURSE
    CALL PRINT_COURSE

ENDPGM:
    MOV AH, 4CH
    INT 21H

PRINT_COURSE PROC
    MOV CX, 6
PRINT_LOOP:
    MOV AL, [SI]
    MOV DL, AL
    MOV AH, 02H
    INT 21H
    INC SI
    LOOP PRINT_LOOP
    MOV DX, OFFSET COURSE_END
    MOV AH, 09H
    INT 21H
    RET
PRINT_COURSE ENDP

END MAIN
